[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "folder2vector"
version = "0.1.0"
authors = [
    { name = "Giuseppe Petraroli", email = "g.petraroli@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "watchdog==6.0.0",
    "PyYAML==6.0.1",
    "langchain",
    "langchain-community",
    "langchain-ollama",
    "langchain-postgres",
    "psycopg[binary]",
    "pypdf",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.3.0",
    "pytest>=8.0.0",
    "mypy>=1.9.0"
]

[project.scripts]
folder2vector = "folder2vector.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]
