[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "folder2vector"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "watchdog==6.0.0",
    "PyYAML==6.0.1",
    "langchain",
    "langchain-community",
    "langchain-ollama",
    "langchain-postgres",
    "psycopg[binary]",
]

[project.scripts]
folder2vector = "folder2vector.main:run"

[tool.setuptools.package-dir]
folder2vector = "src"

[tool.setuptools]
packages = [
    "folder2vector",
    "folder2vector.directory_watcher",
    "folder2vector.vectorizer",
    "folder2vector.vectorizer.file_processor",
]
